version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: clearsystem
    ports:
      - "5432:5432"

  node-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres